# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Swing the bat
tagline:          The Jekyll Butler
url:              http://ziptied.github.io
paginate:         1
baseurl:          /
author:
  name:           Zachary Oakes
  url:            https://twitter.com/ziptied
  email:          zachary.oakes@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ziptied/ziptied
