title:            Swing the bat
tagline:          Lost in translation.
description:      "That's how life is, Sometimes you're the cat, sometimes the mouse."
canonical: http://ziptied.github.io

# Owner/author information
owner:
  name:           Zachary Oakes
  avatar:         avatar.png
  bio:            Lost in translation
  email:          zachary.oakes@gmail.com
  twitter:        ziptied
  github:         ziptied
  instagram:      
  dribbble:       
  location:       "Japan"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
 # - title: About
 #   url: /about
 # - title: Github
 #   url: https://github.com/ColeTownsend/Balzac-for-Jekyll
 #   external: true
  - title: Subscribe
    url: https://tinyletter.com/ziptied
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Japan/Tokyo
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
